#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/6/29 14:40
# @Author  : luoyuediwu
# @Site    : 
# @File    : fields.py
# @Software: PyCharm

f_session = 'session'
f_operations = 'operations'
f_operation_names = 'operation_names'
f_operation = 'operation'
f_id = 'id'
f_key = 'key'
f_pid = 'pid'
f_module = 'module'
f_token = 'token'
f_type = 'type'
f_resource = 'resource'
f_title = 'title'
f_remark = 'remark'
f_comment = 'comment'
f_obsoleted = 'obsoleted'
f_checked = 'checked'
f_next_id = 'next_id'
f_parent_id = 'parent_id'
f_name = 'name'
f_value = 'value'
f_level = 'level'
f_children = 'children'
f_perm = 'perm'
f_perms = 'perms'
f_default_dep = 'default_dep'
f_departments = 'departments'
f_department_count = 'department_count'
f_roles = 'roles'
f_role = 'role'
f_role_count = 'role_count'
f_default_role = 'default_role'
f_super_role = 'super_role'
f_account = 'account'
f_password = 'password'
f_old_password = 'old_password'
f_new_password = 'new_password'
f_email = 'email'
f_phone = 'phone'
f_fax = 'fax'
f_mobile = 'mobile'
f_status = 'status'
f_default_user = 'default_user'
f_user_level = 'user_level'
f_employees = 'employees'
f_employee_count = 'employee_count'
f_USER_ID = 'USER_ID'
f_user_id = 'user_id'
f_used = 'used'
f_display_order = 'display_order'
f_unique_id = 'unique_id'
f_internal = 'internal'
f_owner_id = 'owner_id'
f_location = 'location'
f_license = 'license'
f_url = 'url'
f_tag = 'tag'
f_target = 'target'
f_operation_id = 'operation_id'
f_field = 'field'
f_size = 'size'
f_optional = 'optional'
f_default = 'default'

